using AgentFramework
using Test

include("test_content.jl")
include("test_messages.jl")
include("test_tools.jl")
include("test_sessions.jl")
include("test_chat_client.jl")
include("test_middleware.jl")
include("test_agents.jl")
include("test_structured_output.jl")
include("test_serialization.jl")
include("test_handoffs.jl")
include("test_workflows.jl")
include("test_memory_providers.jl")
include("test_openai_provider.jl")
include("test_anthropic_provider.jl")
include("test_tool_macro.jl")
include("test_multimodal.jl")
include("test_compaction.jl")
include("test_compaction_v2.jl")
include("test_content_filter.jl")
include("test_scoped_state.jl")
include("test_mcp.jl")
include("test_agent_executor.jl")
include("test_protocol.jl")
include("test_telemetry.jl")
include("test_workflow_validation.jl")
include("test_macros.jl")
include("test_declarative.jl")
include("test_capabilities.jl")
include("test_skills.jl")
include("test_resilience.jl")
include("test_extras.jl")
include("test_session_store.jl")
include("test_settings.jl")
include("test_azure_extension.jl")

# Integration tests (require Ollama running)
if get(ENV, "AGENTFRAMEWORK_INTEGRATION", "false") == "true"
    include("test_ollama_integration.jl")
end
